# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0003_auto_20170812_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextend',
            name='salary',
        ),
        migrations.AddField(
            model_name='salary',
            name='user_extend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary', to='theme.UserExtend'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='other',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
